[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = []
[tool.poetry.dependencies]
python = "^3.10"
pygame = "*"
neat-python = "*"
